### ISSUE TITLE
socket  error

### ISSUE THREAD

**Issue by niudali1** [maxtamoian/icmpups#2]
On my computer, sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP);  Then run as an administrator，A message is displayed indicating that the permission is insufficient. If changed to

sock=socket(AF_INET,SOCK_RAW,IPPROTO_ICMP); Then run as an administrator，normal

**Comment by makstamoian** [comment]
This issue seems to be a duplicate of the #1
I've explained the motivation behind choosing to use SOCK_DGRAM there. If you still have questions about it, feel free to comment and contribute!
